apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./istio
  - ./cert-manager
  - ./opa
  - ./monitoring
  - ./reflector
  - ./cloudflare
  - ./kyverno

labels:
  - pairs:
      env: staging
    includeSelectors: true
    includeTemplates: true