apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: victoria-logs
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
    fluxcd.controlplane.io/force: "true"
spec:
  wait: true
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app: victoria-logs
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: victoria-logs
        namespace: flux-system
      spec:
        interval: 5m
        layerSelector:
          mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
          operation: copy
        ref:
          tag: << inputs.version >>
        url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: victoria-logs
        namespace: monitoring
      spec:
        interval: 15m
        timeout: 5m
        maxHistory: 2
        chartRef:
          kind: OCIRepository
          name: victoria-logs
          namespace: flux-system
        install:
          timeout: 10m0s
          remediation:
            retries: 3
        upgrade:
          timeout: 10m0s
          remediation:
            retries: 3
            remediateLastFailure: true
        values:
          server:
            retentionPeriod: "1d"
            persistentVolume:
              enabled: true
              size: 5Gi
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
