apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: opa-staging
  namespace: flux-system
  labels:
    app: opa
spec:
  type: Static
  defaultValues:
    version: "3.23.0"