apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: kiali-platform-sandbox
  namespace: flux-system
  labels:
    app: kiali
spec:
  type: Static
  defaultValues:
    version: "2.7.0"
