apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: monitoring-staging
  namespace: flux-system
  labels:
    app: monitoring
spec:
  type: Static
  defaultValues:
    kubePrometheusStackVersion: "88.1.5"
    tempoVersion: "1.24.4"
    metricsServerVersion: "3.13.1"
    victoriaLogsVersion: "0.13.9"
    otelCollectorVersion: "0.168.0"
