apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: monitoring
type: Opaque
stringData:
    webhookURL: ENC[AES256_GCM,data:nteE8JUgKsDCC3sASi+tQej4qjFa6rAh+Ns4skOh3aTiDxu2mP1lrO++jpdXzPlI5qCL5f4ytZoq59IA7D7SWvfQXkA1MTetnd6w5Iv1Ktuhpfq0DskWAgsE7STGo7lYkk8y52ah2sN1zsEOmZwjgxTpXmHCuqqTVloWcg==,iv:og4s4wPc3niKInbpZFi1F9nOz51manR641NtL2RYoq8=,tag:81tWR62LbhhfqmbVbF0Z3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOEtlRisxT0VHOFZNZEN5
            dHVpRXZqTVhoVERVS3RoWU9JN1pFK1E2WER3CmtHZWVsclVSOU1tenBMR0Q3Vy83
            VzlzL0dNWDIvYkVxRjdTRjE1MTJ4UGsKLS0tICtjZ0tYOTNMRmVTanYzZEw0OVdI
            cndmdXVjU0dWekU0OUt1Ulo2eEkvTlUKntVbLtwe5JS/6bavWmBYDVPTV1rcI5G1
            XKQ09NZrYIZvTqCA9ovzg4LkyIyWT7U5a2yeD+6UtZb3YnRHin1nuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z0se3h2fc40uflwhgeg88szw8qyyuesd9rsxfe962e8pa2t6zaxq5ttmsg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T22:21:01Z"
    mac: ENC[AES256_GCM,data:iyO08n4joA/afIH8cWHm4YDlui4eBSi65LvHhxHPJHXywQ9N88zB0rDrHbTD6YSHWKKRKx0R7TXHH2V2rr5hsBaJXPBQfgbyzq8jp3TEAs/tq0Ur3gzaDNRrCHjFFoNC/MD8a8fDBmstkegYCAKEIW9z6BrXnJm49VZWedgnFy0=,iv:Aam98NNp8BMUSwJi/axg7Uex7CYGqaDZKh3JIg95EEw=,tag:usLr8ORa9jBZJZJTw7+88A==,type:str]
    version: 3.13.3
