apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: istio-gateway
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
    fluxcd.controlplane.io/force: "true"
spec:
  wait: true
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app: istio
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: istio
      namespace: flux-system
      ready: true
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: istio-gateway-api-crds
      namespace: flux-system
      ready: true
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: cert-manager-issuers
      namespace: flux-system
      ready: true
  resources:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: wildcard-tls
        namespace: istio-system
      spec:
        secretName: wildcard-tls
        duration: 2160h # 90 days
        renewBefore: 360h # 15 days
        commonName: "demo-company.site"
        dnsNames:
          - "demo-company.site"
          - "*.demo-company.site"
        issuerRef:
          name: letsencrypt-production
          kind: ClusterIssuer
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gw-options
        namespace: istio-system
      data:
        deployment: |
          spec:
            replicas: 2
            template:
              spec:
                tolerations:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
                    effect: NoSchedule
        service: |
          spec:
            # With cloudflare tunnel , we can drop the need for a LoadBalancer and use ClusterIP instead
            type: ClusterIP
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: gateway
        namespace: istio-system
      spec:
        gatewayClassName: istio
        infrastructure:
          parametersRef:
            group: ""
            kind: ConfigMap
            name: gw-options
        listeners:
          - name: https
            port: 443
            protocol: HTTPS
            hostname: "*.demo-company.site"
            tls:
              mode: Terminate
              certificateRefs:
                - name: wildcard-tls
            allowedRoutes:
              namespaces:
                from: All