apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: kube-prometheus-stack-app-dev
  namespace: flux-system
  labels:
    app: kube-prometheus-stack
spec:
  type: Static
  defaultValues:
    version: "88.1.5"
    domain: "app-dev.demo-company.site"
