apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:XJasW8NBKe6vfyu6hR1ZRP1ciXLyj6H9kyQ/5S/xupMWIh0HBlp3J+QPVhfyflDIgj4EACY=,iv:409zbwlu2vsQuVpYW2b9ZijjquXETORpYJjrKVdHniI=,tag:ODn0OsnEPE0k4glmFQe9hA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M2pwazZMQk1UVGoyblFI
            eU1zOUJUNHo5SHBvYUFacnZpb2FFRkFBc0FJCm12bmlEMDRoLzEzM1BuamE5aGtn
            MU1Rbm9MRlNONzlwVjhqNTZoUlk1aGcKLS0tIHRqZ0JsMmpQa3FzWU93U00rUVJz
            V211UGpNVGZiVGErQkh0cTBGZEgxNGsK+FgLx95m9ClmQ009hRqHyIoQ0AtxulJT
            wTPYV9OVKa/5TDnh1CUSR91Vqrgy5meZoXI3mz0oDlcNCbjifaO2rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z0se3h2fc40uflwhgeg88szw8qyyuesd9rsxfe962e8pa2t6zaxq5ttmsg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T19:57:05Z"
    mac: ENC[AES256_GCM,data:3bSQU/5oPphNu25vN0OR6UGfPx3EAQVOVIBqj7mosziJBJUwvmV5tTsy6Fp4Qk8YwZpYMhsT/6uLaQuybkJsS75k+lyzfyhYJdue9GK/EHWzzo0UXSAvf8bhmkIa2fw5A/1SDH31Pq0CsubTenEXqwA0JMuGIZVUu2Tr80kEkEk=,iv:em/mlplEn7yYX2ha//qovAjUVJcL3y8+SeNVV2kVilQ=,tag:Kzkb43bQrw7tEiQHtLQJYQ==,type:str]
    version: 3.13.3
