apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: team-namespaces
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
    fluxcd.controlplane.io/force: "true"
spec:
  inputs:
    - team: application
      environment: prod
      cpu: "2"
      memory: "4Gi"
      cpuLimit: "4"
      memoryLimit: "8Gi"
      maxPods: "20"
