apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: monitoring
type: Opaque
stringData:
    webhookURL: ENC[AES256_GCM,data:05dvRXV6hgeuWdoRoyyJX12wXAlrqj3J+s4PU+o+bGwcx3W12J0DhNAD39sDPzs+c6nUQ5qJi4rjeRsnkSaYZFJdIkEP+7081NQYErC65RXInGd5Ep95ny9qV7/VCEmc5gXq/UirgsB6WDyiWOfS+r72GdD43itL9tdpVg==,iv:6oHLyJ/vBEoD1TFDKgjgZEotPRhT9FtXclhAz5S58ig=,tag:lyNOPOOOEn4D+N8RZXk9mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNHk2MUJNdWhubkNxM0Rv
            L0xQVk1paEM3NDA3Z1doVVFwNDZYWUx0VjBNClFGMGcrZitnWkpHNjc0U29nTldp
            TUxQY1Rta0dEY0dIbGhzSDE1dmNMWG8KLS0tIDEvV0VJRTdIRi9Zamx4OStzNW1D
            b09YT2JhTlBwOS8zUDZ0VC8wZm5EVXcKwOPL+uhVyPnaq+37rXZoxGkk5PAOOPvM
            bdqCcxkU+Et+1AUgm6dPoY/A2kvBxetD1mPd5+z9ZXQLn+uZnfMRgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z0se3h2fc40uflwhgeg88szw8qyyuesd9rsxfe962e8pa2t6zaxq5ttmsg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T17:19:28Z"
    mac: ENC[AES256_GCM,data:P0QRKjsrVX0AquTZzF/E90cs1K/Bxs3dHvg0l2Nb5O2P4hzDVFmJtrcriUOgs+26Dkj5qBgwe96JpDO0NjVXi69L5ivkN7oR2IEE6VL1hr+4fa4LOVDD9N2FDwz3MpIk94/ri541esIIFCLaPPOeNCI9iEvqI1PnUzg7FDUcxAo=,iv:kLg0972+x+aAcYlzMGE77yCE5d7mGPMS7uVI7s0Qwd8=,tag:mRlKpLlpZM9L1qgV8zPpEw==,type:str]
    version: 3.13.3
