apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: kiali
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
    fluxcd.controlplane.io/force: "true"
spec:
  wait: true
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app: kiali
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: istio-gateway
      namespace: flux-system
      ready: true
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: kube-prometheus-stack
      namespace: flux-system
      ready: true
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: kiali
        namespace: flux-system
      spec:
        interval: 1h
        url: https://kiali.org/helm-charts
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: kiali
        namespace: istio-system
      spec:
        interval: 10m
        chart:
          spec:
            chart: kiali-server
            version: "<< inputs.version >>"
            sourceRef:
              kind: HelmRepository
              name: kiali
              namespace: flux-system
        install:
          createNamespace: false
          timeout: 5m
          remediation:
            retries: 3
        upgrade:
          timeout: 5m
          remediation:
            retries: 3
            remediateLastFailure: true
        values:
          auth:
            strategy: anonymous
          external_services:
            prometheus:
              url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            grafana:
              enabled: true
              url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
            tracing:
              enabled: false
          deployment:
            accessible_namespaces:
              - "**"
