apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: reflector-platform-sandbox
  namespace: flux-system
  labels:
    app: reflector
spec:
  type: Static
  defaultValues:
    version: "10.0.63"